# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vishal Gupta
email: guptavis@usc.edu
description: Researcher and teacher focusing on data-driven decision-making, optimization, operations research and statistics.
  
baseurl: "/Vishal-Gupta" # the subpath of your site, e.g. /blog
#url: "http://example.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  vgupta1

## Some Stuff to make the theme work.
academic_email: guptavis@usc.edu
googlescholar_username: KZcnoikAAAAJ&hl  #Weirdo google scholar encoding

##Nav bar is set by editing the _menu.yml file in _data folder

# Build settings
# markdown: kramdown
#theme: minima
remote_theme: ys1998/academic-portfolio
collections:
  - papers
